const dmatlackRoms = [
    "demos/Maze (alt) [David Winter, 199x].ch8",
    "demos/Maze [David Winter, 199x].ch8",
    "demos/Particle Demo [zeroZshadow, 2008].ch8",
    "demos/Sierpinski [Sergey Naydenov, 2010].ch8",
    "demos/Stars [Sergey Naydenov, 2010].ch8",
    "demos/Trip8 Demo (2008) [Revival Studios].ch8",
    "demos/Zero Demo [zeroZshadow, 2007].ch8",
    "games/15 Puzzle [Roger Ivie] (alt).ch8",
    "games/15 Puzzle [Roger Ivie].ch8",
    "games/Addition Problems [Paul C. Moews].ch8",
    "games/Airplane.ch8",
    "games/Animal Race [Brian Astle].ch8",
    "games/Astro Dodge [Revival Studios, 2008].ch8",
    "games/Biorhythm [Jef Winsor].ch8",
    "games/Blinky [Hans Christian Egeberg, 1991].ch8",
    "games/Blinky [Hans Christian Egeberg] (alt).ch8",
    "games/Blitz [David Winter].ch8",
    "games/Bowling [Gooitzen van der Wal].ch8",
    "games/Breakout (Brix hack) [David Winter, 1997].ch8",
    "games/Breakout [Carmelo Cortez, 1979].ch8",
    "games/Brick (Brix hack, 1990).ch8",
    "games/Brix [Andreas Gustafsson, 1990].ch8",
    "games/Cave.ch8",
    "games/Coin Flipping [Carmelo Cortez, 1978].ch8",
    "games/Connect 4 [David Winter].ch8",
    "games/Craps [Camerlo Cortez, 1978].ch8",
    "games/Deflection [John Fort].ch8",
    "games/Figures.ch8",
    "games/Filter.ch8",
    "games/Guess [David Winter] (alt).ch8",
    "games/Guess [David Winter].ch8",
    "games/Hi-Lo [Jef Winsor, 1978].ch8",
    "games/Hidden [David Winter, 1996].ch8",
    "games/Kaleidoscope [Joseph Weisbecker, 1978].ch8",
    "games/Landing.ch8",
    "games/Lunar Lander (Udo Pernisz, 1979).ch8",
    "games/Mastermind FourRow (Robert Lindley, 1978).ch8",
    "games/Merlin [David Winter].ch8",
    "games/Missile [David Winter].ch8",
    "games/Most Dangerous Game [Peter Maruhnic].ch8",
    "games/Nim [Carmelo Cortez, 1978].ch8",
    "games/Paddles.ch8",
    "games/Pong (1 player).ch8",
    "games/Pong (alt).ch8",
    "games/Pong 2 (Pong hack) [David Winter, 1997].ch8",
    "games/Pong [Paul Vervalin, 1990].ch8",
    "games/Programmable Spacefighters [Jef Winsor].ch8",
    "games/Puzzle.ch8",
    "games/Reversi [Philip Baltzer].ch8",
    "games/Rocket Launch [Jonas Lindstedt].ch8",
    "games/Rocket Launcher.ch8",
    "games/Rocket [Joseph Weisbecker, 1978].ch8",
    "games/Rush Hour [Hap, 2006] (alt).ch8",
    "games/Rush Hour [Hap, 2006].ch8",
    "games/Russian Roulette [Carmelo Cortez, 1978].ch8",
    "games/Sequence Shoot [Joyce Weisbecker].ch8",
    "games/Shooting Stars [Philip Baltzer, 1978].ch8",
    "games/Slide [Joyce Weisbecker].ch8",
    "games/Soccer.ch8",
    "games/Space Flight.ch8",
    "games/Space Intercept [Joseph Weisbecker, 1978].ch8",
    "games/Space Invaders [David Winter] (alt).ch8",
    "games/Space Invaders [David Winter].ch8",
    "games/Spooky Spot [Joseph Weisbecker, 1978].ch8",
    "games/Squash [David Winter].ch8",
    "games/Submarine [Carmelo Cortez, 1978].ch8",
    "games/Sum Fun [Joyce Weisbecker].ch8",
    "games/Syzygy [Roy Trevino, 1990].ch8",
    "games/Tank.ch8",
    "games/Tapeworm [JDR, 1999].ch8",
    "games/Tetris [Fran Dachille, 1991].ch8",
    "games/Tic-Tac-Toe [David Winter].ch8",
    "games/Timebomb.ch8",
    "games/Tron.ch8",
    "games/UFO [Lutz V, 1992].ch8",
    "games/Vers [JMN, 1991].ch8",
    "games/Vertical Brix [Paul Robson, 1996].ch8",
    "games/Wall [David Winter].ch8",
    "games/Wipe Off [Joseph Weisbecker].ch8",
    "games/Worm V4 [RB-Revival Studios, 2007].ch8",
    "games/X-Mirror.ch8",
    "games/ZeroPong [zeroZshadow, 2007].ch8",
    "hires/Astro Dodge Hires [Revival Studios, 2008].ch8",
    "hires/Hires Maze [David Winter, 199x].ch8",
    "hires/Hires Particle Demo [zeroZshadow, 2008].ch8",
    "hires/Hires Sierpinski [Sergey Naydenov, 2010].ch8",
    "hires/Hires Stars [Sergey Naydenov, 2010].ch8",
    "hires/Hires Test [Tom Swan, 1979].ch8",
    "hires/Hires Worm V4 [RB-Revival Studios, 2007].ch8",
    "hires/Trip8 Hires Demo (2008) [Revival Studios].ch8",
    "programs/BMP Viewer - Hello (C8 example) [Hap, 2005].ch8",
    "programs/Chip8 Picture.ch8",
    "programs/Chip8 emulator Logo [Garstyciuks].ch8",
    "programs/Clock Program [Bill Fisher, 1981].ch8",
    "programs/Delay Timer Test [Matthew Mikolay, 2010].ch8",
    "programs/Division Test [Sergey Naydenov, 2010].ch8",
    "programs/Fishie [Hap, 2005].ch8",
    "programs/Framed MK1 [GV Samways, 1980].ch8",
    "programs/Framed MK2 [GV Samways, 1980].ch8",
    "programs/IBM Logo.ch8",
    "programs/Jumping X and O [Harry Kleinberg, 1977].ch8",
    "programs/Keypad Test [Hap, 2006].ch8",
    "programs/Life [GV Samways, 1980].ch8",
    "programs/Minimal game [Revival Studios, 2007].ch8",
    "programs/Random Number Test [Matthew Mikolay, 2010].ch8",
    "programs/SQRT Test [Sergey Naydenov, 2010].ch8",
].map(s => "https://github.com/dmatlack/chip8/tree/master/roms/" + s)

const corax89Roms = [
    "https://github.com/corax89/chip8-test-rom/blob/master/test_opcode.ch8"
]

export const roms = dmatlackRoms.concat(corax89Roms)

export const defaultRom = corax89Roms[0]

export function toDownloadUrl(url: string) {
    url = url.replace("https://github.com", "https://raw.githubusercontent.com")
    url = url.replace("/tree/", "/")
    url = url.replace("/blob/", "/")
    return url
}

export function toInfoUrl(url: string) {
    // Works for https://github.com/dmatlack/chip8
    url = url.replace(' (alt)', '')
    url = url.replace('.ch8', '.txt')
    return url
}
